Update note_entry.lua
finale-lua/lua-scripts pull request #515
Opened 2023-04-30 22:44 UTC by cv-on-hub

A good idea to include PerfMod deletions?

also ...

in `note_entry.rest_offset()` setting offset to zero is different from wanting a `FloatingRest`. Shouldn't there be an additional boolean input: `zero_is_floating`
???

2023-04-30 23:46 UTC, cv-on-hub commented
Actually, to limit breakage, the additional boolean input should be: `zero_not_floating `

2023-04-30 23:52 UTC, rpatters1 commented
Personally I dislike boolean inputs and prefer to avoid them when possible. Doesn't the PDK have a call to make it floating? Does that need to be duplicated here?

2023-04-30 23:59 UTC, cv-on-hub commented
`entry:SetRestDisplacement()`automatically makes the rest movable, not floating. An explicit `entry:SetFloatingRest(true)` could reasonably be left up to the user.

2023-05-04 12:36 UTC, rpatters1 requested changes
I would like to see this change replaced with a single line, similar to the rest of the function:

```lua
finale.FCPerformanceMod():EraseAt(note)
```

The `EraseAt` method takes care of all necessary checks. (Actually, we should not check the flag because it isn't reliable for removing cruft, but `EraseAt` takes care of it.)

2023-05-04 12:49 UTC, rpatters1 commented
I'm a big believer in if it ain't broke don't fix it. Is the function not doing what it needs to now?

2023-05-04 15:30 UTC, rpatters1 commented
I will go ahead and merge this. If `rest_offset` needs further attention it can be a separate PR.

2023-05-04 15:30 UTC, merged